id: P007063
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8724
  title: 'དྭགས་པོ་གྲྭ་ཚང་གི་ཡིག་ཆ། '
  author: ''
  volumes:
    79cf18cfbbca4bb89bd47943f04e43b2:
      image_group_id: I1KG8746
      title: Volume 1 of dwags po grwa tshang gi yig cha/
      volume_number: 1
      total_pages: 506
      base_file: v001.txt
    a6ff411dbd0c4a17935082196b3a889f:
      image_group_id: I1KG8747
      title: Volume 2 of dwags po grwa tshang gi yig cha/
      volume_number: 2
      total_pages: 398
      base_file: v002.txt
    d9d0d9ff63ee4979bd078424b169592a:
      image_group_id: I1KG8748
      title: Volume 3 of dwags po grwa tshang gi yig cha/
      volume_number: 3
      total_pages: 190
      base_file: v003.txt
    ced0c05b15224ee3a4d455dac602cee1:
      image_group_id: I1KG8749
      title: Volume 4 of dwags po grwa tshang gi yig cha/
      volume_number: 4
      total_pages: 35
      base_file: v004.txt
    28a72f974ab04a84874c4711bc806401:
      image_group_id: I1KG8750
      title: Volume 5 of dwags po grwa tshang gi yig cha/
      volume_number: 5
      total_pages: 50
      base_file: v005.txt
ebook_metadata:
  title: 'དྭགས་པོ་གྲྭ་ཚང་གི་ཡིག་ཆ། '
  author: ''
  sku: P007063
  cover: cover.jpg
  layers:
  - pagination
