id: P007063
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8724
  title: 'དྭགས་པོ་གྲྭ་ཚང་གི་ཡིག་ཆ། '
  author: ''
  volumes:
    a109c0f0c5b8419fa371a3559799a54e:
      image_group_id: I1KG8746
      title: ''
      volume_number: 1
      total_pages: 506
    6f23e411353442caa7a016e0fbb2b75a:
      image_group_id: I1KG8747
      title: ''
      volume_number: 2
      total_pages: 398
    c2b8eef70d25413286aac74e728cb4ac:
      image_group_id: I1KG8748
      title: ''
      volume_number: 3
      total_pages: 190
    2c0e05cf2e5742efbb064cb0cc10c354:
      image_group_id: I1KG8749
      title: ''
      volume_number: 4
      total_pages: 35
    02925970fdfd49c082e3721ced23dba5:
      image_group_id: I1KG8750
      title: ''
      volume_number: 5
      total_pages: 50
ebook_metadata:
  title: 'དྭགས་པོ་གྲྭ་ཚང་གི་ཡིག་ཆ། '
  author: ''
  sku: P007063
  cover: cover.jpg
  layers:
  - pagination
