id: IC40D403D
legacy_id: P007063
ocr_import_info:
  bdrc_scan_id: W1KG8724
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T16:50:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:01:49.630790+00:00'
last_modified: 2022-09-01 02:02:35.228097
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG8724
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG8724
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྭགས་པོ་གྲྭ་ཚང་གི་ཡིག་ཆ།
  author: དྭགས་པོ་མཁས་གྲུབ་བྱམས་པ་བརྟན་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6227443057757563
  ocr_word_median_confidence_index: 0.6299999952316284
quality: null
bases:
  I1KG8746:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8746
      total_pages: 506
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG8746.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6489373487806487
    legacy_id: v001
  I1KG8750:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8750
      total_pages: 50
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG8750.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5859559147445129
    legacy_id: v005
  I1KG8747:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8747
      total_pages: 398
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG8747.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5976839776116366
    legacy_id: v002
  I1KG8748:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8748
      total_pages: 190
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG8748.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6250549172070282
    legacy_id: v003
  I1KG8749:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8749
      total_pages: 35
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG8749.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.6106165707995256
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
