id: IC40D403D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T16:51:31+00:00'
last_modified: '2022-06-08T16:29:16.117589+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8724
  title: 'དྭགས་པོ་གྲྭ་ཚང་གི་ཡིག་ཆ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4873':
      image_group_id: I1KG8746
      title: Volume 1 of dwags po grwa tshang gi yig cha/
      total_pages: 506
      order: 1
      base_file: 4873.txt
    C3DB:
      image_group_id: I1KG8747
      title: Volume 2 of dwags po grwa tshang gi yig cha/
      total_pages: 398
      order: 2
      base_file: C3DB.txt
    E56A:
      image_group_id: I1KG8748
      title: Volume 3 of dwags po grwa tshang gi yig cha/
      total_pages: 190
      order: 3
      base_file: E56A.txt
    D8D8:
      image_group_id: I1KG8749
      title: Volume 4 of dwags po grwa tshang gi yig cha/
      total_pages: 35
      order: 4
      base_file: D8D8.txt
    '9497':
      image_group_id: I1KG8750
      title: Volume 5 of dwags po grwa tshang gi yig cha/
      total_pages: 50
      order: 5
      base_file: 9497.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
